---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 邱佳慧.
--- DateTime: 2025/8/1 20:23
---

local key = KEYS[1]
local window = tonumber(ARGV[1])
local limit = tonumber(ARGV[2])
local now = tonumber(ARGV[3])

if not key or key == '' or not window or not limit or not now then
    return redis.error_reply("")
end

window = window*1000;
redis.call('ZREMRANGEBYSCORE', key, 0, now-window)

local current = redis.call('ZCARD', key)

if current<limit then
    math.randomseed(now)
    local random = math.random(1000000)
    redis.call('ZADD', key, now, now .. '-' .. random)
    -- 更新过期时间 通过EXPIRE让整个Key过期
    redis.call('EXPIRE', key, window/1000)
    return current+1
else
    return 0
end