---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 邱佳慧.
--- DateTime: 2025/5/23 19:19
---

if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0